language: r
warnings_are_errors: true
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-manual"

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: osx
      r: devel


addons:
  apt:
    packages:
      - libssl1.0.0
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::coveralls()'
