language: r
warnings_are_errors: true
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-manual --as-cran"

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release


addons:
  apt:
    packages:
      - libssl1.0.0
r_packages:
  - covr
  - lintr
before_test: 
  - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'covr::coveralls()'
